### ISSUE TITLE
Wrong diff generated if key string contains dot.

### ISSUE THREAD

**Issue by wangyifan** [inveniosoftware/dictdiffer#101]
The following code will break for v0.7.0:

```python
from dictdiffer import diff, patch

first = {
         "a.b": {
              "c.d": 1
         }
}

second = {
         "a.b": {
              "c.d": 2
         }
}

_diff = diff(first, second)
patch(_diff, first)
```

Exception:

```
Traceback (most recent call last):
  File "b.py", line 16, in <module>
    patch(_diff, first)
  File "/nail/home/yifan/virtualenv_run/lib/python2.7/site-packages/dictdiffer/__init__.py", line 308, in patch
    patchers[action](node, changes)
  File "/nail/home/yifan/virtualenv_run/lib/python2.7/site-packages/dictdiffer/__init__.py", line 283, in change
    dest = dot_lookup(destination, node, parent=True)
  File "/nail/home/yifan/virtualenv_run/lib/python2.7/site-packages/dictdiffer/utils.py", line 251, in dot_lookup
    value = value[key]
KeyError: 'a'
```

Can we always use list ['a', 'b', 'c', 'd'] instead of string 'a.b.c.d' to represent a path in the dict?

**Comment by jirikuncar** [comment]
@wangyifan can you please test the fix from PR #102? Thanks!

**Comment by wangyifan** [comment]
@jirikuncar I applied the diff and it worked. Thank you for fixing this.

Do you plan to make a new release?

**Comment by jirikuncar** [comment]
@wangyifan yes, we will do one, but I can't promise an exact date.

**Comment by wangyifan** [comment]
@jirikuncar Will that be usually in days, weeks, or months? I am investigating if my company can use this package in our project. I don't need an exact date now but just want to plan accordingly.

**Comment by jirikuncar** [comment]
I hope in "weeks" or less.
