### ISSUE TITLE
ignore non-overlapping keys

### ISSUE THREAD

**Issue by mlund** [inveniosoftware/dictdiffer#113]
As part of unit testing, I'd like to use dictdiffer to compare stable/correct output (with tolerance) from a scientific simulation with potentially buggy development output. Newer versions of the tool may output additional keys that need/can not be compared and a flag to skip non-overlapping keys would be very useful.

**Comment by mlund** [comment]
For example, this could be output from an **old** version that is known to give correct results, and the output if only rarely re-generated,

~~~~ yaml
moves:
-   translate:
        acceptance: 0.657
~~~~

and this is output from a **development** version that may not work and may add addtional keys:
~~~~ yaml
moves:
-   translate:
        acceptance: 0.659
        time: 0.73
~~~~

Ideally, something like this would be great,

~~~~ python
    # import YAML to dict etc...
    dictdiffer.diff(old, dev, ignoremissing=True, tolerance=0.01)
~~~~

**Comment by jirikuncar** [comment]
@mlund can you run filter on the diff result and ignore `remove` patches?

```python
diff = (patch for patch in dictdiffer.diff(old, dev, tolerance=0.01) if patch[0] != 'remove')
```

**Comment by jirikuncar** [comment]
@mlund feel free to re-open if the proposed solution doesn't help you.
