### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by nilsnolde** [inveniosoftware/dictdiffer#116]
Last commit is 9 months ago, some issues are more than a year old.

Could you pls update us if this library plans to stay maintained or you're looking for new maintainers?

**Comment by nilsnolde** [comment]
uff, my bad.. github seems to have problems with the dates indicating when files were last changed..

**Comment by lnielsen** [comment]
It's being maintained, let me know if you have an interest in helping out.
