### ISSUE TITLE
Release v1.0?

### ISSUE THREAD

**Issue by milesgranger** [inveniosoftware/dictdiffer#132]
Hello, and thanks for the helpful project you have here.

Looking through the issues, lack of recent commits to the lib and the [milestone](https://github.com/inveniosoftware/dictdiffer/milestone/6) seems complete; is there anything else holding up a 1.0 release?

**Comment by jirikuncar** [comment]
@milesgranger all functionality merged to master is available in 0.8.0. There are several open issues which might change the internals (and possibly API) of this package. We are doing releases as needed with a best effort to keep backward compatibility.
