### ISSUE TITLE
KeyError on differenct dicts

### ISSUE THREAD

**Issue by gdassori** [inveniosoftware/dictdiffer#138]
Hi, given two different dictionaries where the second lacks the diff REMOVE key, I'm asking if this is the expected behaviour: 

```
>>> dictdiffer.patch(dictdiffer.diff({'b': ''}, {'a': ''}), {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/dictdiffer/__init__.py", line 330, in patch
    patchers[action](node, changes)
  File "/usr/local/lib/python3.5/site-packages/dictdiffer/__init__.py", line 321, in remove
    del dest[key]
KeyError: 'b'
>>> dictdiffer.__version__
'0.8.0'
```

**Comment by mikaelho** [comment]
I would say this is expected. Your diff says ”remove b, add a”, and then you apply it to an empty dict, so you get an error saying ”cannot remove b”.

**Comment by jirikuncar** [comment]
@gdassori the correct usage should be:

```python
>>> a = {'a': ''}
>>> b = {'b': ''}
>>> dictdiffer.patch(dictdiffer.diff(b, a), b)
{'a': ''}
```
you have to apply the patch to the object from which you have calculated the diff.
