### ISSUE TITLE
get wrong result with path_limit

### ISSUE THREAD

**Issue by hugebig** [inveniosoftware/dictdiffer#172]
Package version (if known): <0.9.0>

## Describe the bug
a = {'a': [{'a': 1, 'b': 2}], 'b': {'a': 1}}
b = {'a': [{'a': 1, 'b': 2}], 'b': {'a': 1}}
result = diff(a, b, path_limit=[('a',)])
print(list(result))
`[('change', ['a'], ([{'a': 1, 'b': 2}], [{'a': 1, 'b': 2}]))]`

## Expected behavior
[]

**Comment by lkrash84** [comment]
Hi! There is still an issue probably (v0.9.0):

```python
a = {'input': {}, 'output': {}, 'forward': {'WWW': {...}}}
b = {'input': {}, 'output': {}, 'forward': {'WWW': {...}, 'FTP': {...}}}

dictdiffer.diff(a, b, dot_notation=False, path_limit=[('*', '*')])
```
gives `[]`

expected behaviour:

```python
[["add", ["forward"], [["FTP", {...}]]]]
```
