### ISSUE TITLE
reports NO-OP has occured when diffing lists

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware/dictdiffer#48]
```python
In [1]: from dictdiffer import diff

In [2]: d={1: [1]}; list(diff(d, d))
Out[2]: [('remove', '1', [])]
```

@mvesper is working on this. This report is for reference.

**Comment by jirikuncar** [comment]
works for me (see #49)

**Comment by dset0x** [comment]
Invalid, please close @jirikuncar. My shell was importing from an old directory without me having noticed.
