### ISSUE TITLE
NaN comparison

### ISSUE THREAD

**Issue by thehesiod** [inveniosoftware/dictdiffer#54]
right now NaNs compare as different, here's a patch to __init__.py to fix it:

-        if first != second:
+        if first != second and [first] != [second]:

**Comment by jirikuncar** [comment]
@thehesiod thank you! Can you please submit a pull-request with a test case?

**Comment by thehesiod** [comment]
https://github.com/inveniosoftware/dictdiffer/pull/55 <https://github.com/inveniosoftware/dictdiffer/pull/55>
