### ISSUE TITLE
Handling of arrays

### ISSUE THREAD

**Issue by mikaelho** [inveniosoftware/dictdiffer#85]
Using dictdiffer 0.6.0, I get a list index out of range with the following code, probably because when reverting, the list elements are removed in the wrong order.

    from dictdiffer import diff, patch, swap, revert

    one = { 
       'one': ['is two']
     }
    two = { 
       'one': ['is two', 'is three', 'is four']
    }

    result_diff = diff(one, two)
    print revert(result_diff, two)

**Comment by jirikuncar** [comment]
@mikaelho thanks for the bug report. Can you please verify if #86 fixes your problem? Thanks!

**Comment by mikaelho** [comment]
Thanks, works, also when the changed array elements are elsewhere than the end of the list.
