### ISSUE TITLE
Immutable diffs

### ISSUE THREAD

**Issue by mikaelho** [inveniosoftware/dictdiffer#89]
Current implementation returns diffs that reference the original structure. Thus the diff may change later when the structures change.

This is counter to at least my intuitive expectation that the diff is a snapshot of the structures at the time of running the diff.

I would request that the diff returns (deep) copies of the referenced structures by default, with maybe an option for returning references instead.

At the very least I recommend making this very explicit in the documentation - I just suffered from some very hard to debug bugs because of this.

Thanks!

**Comment by jirikuncar** [comment]
@mikaelho thank you for the proposal. Are you willing to submit a test case and a patch?

**Comment by mikaelho** [comment]
Here's a test case where the second assert fails. I am not a coder enough to submit a patch -- currently I am just wrapping diff calls with deepcopy.

    from dictdiffer import diff
    
    one = { 'one': 'one' }
    two = { 'one': {'two': 'three' }}
    
    result = list(diff(one, two))
    # [('change', 'one', ('one', {'two': 'three'}))]
    
    assert result[0][2][1]['two'] == 'three'
    
    two['one']['two'] = 'four'
    
    assert result[0][2][1]['two'] == 'three'

**Comment by jirikuncar** [comment]
closed via #90
