### ISSUE TITLE
Support in-place patch/revert

### ISSUE THREAD

**Issue by mikaelho** [inveniosoftware/dictdiffer#91]
I request adding an in-place patch/revert capability, i.e. option for performing these operations without copying the target structure.

This would be a useful performance optimization in some large-volume use cases. I also have a functional need of patching in place while recording all changes made to the structure.

This could be implemented as an additional, optional parameter to patch and revert:

Patch:

    def patch(diff_result, destination, in_place=False):
        """Docstring"""
        if not in_place:
          destination = copy.deepcopy(destination)
      
Revert:

    def revert(diff_result, destination, in_place=False):
        """Docstring"""
        return patch(swap(diff_result), destination, in_place)

And tested with e.g.

    a = {
      'a' : 1
    }
    b = {
      'a' : 2
    }
    changes = list(diff(a, b))
    
    c = patch(changes, a)
    assert a != c
    
    d = revert(changes, c, in_place=True)
    assert a == d
    assert c == d
    
    e = patch(changes, a, in_place=True)
    assert a == e

**Comment by jirikuncar** [comment]
@mikaelho are you willing to send a pull-request with proposed tests?

**Comment by mikaelho** [comment]
Never done it before. I will try.

**Comment by jirikuncar** [comment]
@mikaelho don't worry 😉  Just have a look at some past commits to see how things are done. If you have any question just ping me.

**Comment by mikaelho** [comment]
Done - my first pull request ever.

https://github.com/inveniosoftware/dictdiffer/pull/92
